### ISSUE TITLE
Clicking sounds when in reset

### ISSUE THREAD

**Issue by phoboz** [phoboz/fpgagen#8]
Unwanted sounds can be removed by muting the sound output while in reset.

**Comment by jotego** [comment]
Amplifier is now muted during rst but that did not solve the issue.

**Comment by phoboz** [comment]
I didn't hear any clicking sounds now when jt12 0.3 is used, so this must be fixed now. However when changing games, there can still be a tone until the next game is loaded.

**Comment by jotego** [comment]
Yes, I spent time in making sure that initial reset was quiet.
I have also heard the noise in between games. Is reset signal asserted while the user chooses a new game or do we get a single reset pulse?

**Comment by robinsonb5** [comment]
A single reset pule so that the video subsystem remains live, otherwise there's nothing for the OSD to overlay its image against.  (There's a separate bootdone signal that's folded into the CPU's reset signal - there's no reason why this couldn't be added to the FM's reset signal too - that would solve the problem, yes?)

**Comment by jotego** [comment]
I have fixed it in the _Next_ branch. I will merge it later.
